/**
 * PushToGitHubDialog — pushes a finished Vibe/Smart-generation run (generated
 * code + project model) to a GitHub repo.
 *
 * Modes:
 *   - UPDATE   — a ``'github'`` link already exists for this project. Shows the
 *                linked ``owner/repo@branch`` banner + commit message, with
 *                "Change repo" to unlink and fall back to CREATE/SELECT.
 *   - CREATE   — create a brand-new repo (name / description / private default).
 *   - EXISTING — pick one of the user's repos + a branch and push into it.
 *
 * State (open/link/result/push) is owned by ``useSpecDrivenGithubPush``; this
 * component owns only its form fields and the repo/branch picker.
 */

import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ExternalLink, Github, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { FormField } from '@/components/ui/form-field';
import { validateRepoName } from '../../../shared/utils/validation';
import { useFieldValidation } from '../../../shared/hooks/useFieldValidation';
import type { DeployLinkedRepo } from '../../../shared/services/storage/local-storage-repository';
import { useGitHubStorage } from '../hooks/useGitHubStorage';
import type {
  SpecDrivenPushConfig,
  SpecDrivenPushResult,
  SpecDrivenPushOutcome,
} from '../hooks/useSpecDrivenGithubPush';

const DEFAULT_BRANCH = 'main';

/** Mirror DeployMenu's repo-name sanitizer for the create-new default. */
const sanitizeRepoName = (name: string): string =>
  name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '');

const defaultRepoName = (projectName: string): string =>
  sanitizeRepoName(projectName) || 'besser-app';

export interface PushToGitHubDialogProps {
  open: boolean;
  runId: string | null;
  projectName: string;
  linkedRepo: DeployLinkedRepo | null;
  githubSession: string | null;
  isPushing: boolean;
  result: SpecDrivenPushResult | null;
  onOpenChange: (open: boolean) => void;
  onChangeRepo: () => void;
  push: (config: SpecDrivenPushConfig) => Promise<SpecDrivenPushOutcome>;
}

export const PushToGitHubDialog: React.FC<PushToGitHubDialogProps> = ({
  open,
  projectName,
  linkedRepo,
  githubSession,
  isPushing,
  result,
  onOpenChange,
  onChangeRepo,
  push,
}) => {
  const { repositories, isLoading: reposLoading, fetchRepositories, fetchBranches } = useGitHubStorage();

  const isUpdateMode = !!linkedRepo && !result;

  // ── Form state ─────────────────────────────────────────────────────────
  const [mode, setMode] = useState<'create' | 'existing'>('create');
  const [repoName, setRepoName] = useState('');
  const [description, setDescription] = useState('');
  const [isPrivate, setIsPrivate] = useState(true);
  const [createBranch, setCreateBranch] = useState(DEFAULT_BRANCH);
  const [commitMessage, setCommitMessage] = useState('');

  // Existing-repo picker
  const [selectedRepoFullName, setSelectedRepoFullName] = useState('');
  const [branches, setBranches] = useState<string[]>([]);
  const [selectedBranch, setSelectedBranch] = useState('');
  const [loadingBranches, setLoadingBranches] = useState(false);

  const [inlineError, setInlineError] = useState<string | null>(null);

  // ── Inline validation (create-new mode only) ───────────────────────────
  const validators = useMemo(
    () => ({
      repoName: () => (mode === 'create' && !isUpdateMode ? validateRepoName(repoName) : undefined),
    }),
    [mode, isUpdateMode, repoName],
  );
  const validation = useFieldValidation(validators);

  // Initialize the form on the rising edge of ``open`` so re-renders while the
  // dialog is up don't wipe what the user is typing.
  const wasOpenRef = useRef(false);
  useEffect(() => {
    if (open && !wasOpenRef.current) {
      setMode('create');
      setRepoName(defaultRepoName(projectName));
      setDescription(`Generated by BESSER — ${projectName || 'project'}`);
      setIsPrivate(true);
      setCreateBranch(DEFAULT_BRANCH);
      setCommitMessage('');
      setSelectedRepoFullName('');
      setBranches([]);
      setSelectedBranch('');
      setInlineError(null);
      validation.resetTouched();
    }
    wasOpenRef.current = open;
  }, [open, projectName, validation]);

  // Lazy-load repositories when the user first switches to "Use existing".
  useEffect(() => {
    if (!open || mode !== 'existing' || !githubSession) return;
    if (repositories.length > 0 || reposLoading) return;
    void fetchRepositories(githubSession);
  }, [open, mode, githubSession, repositories.length, reposLoading, fetchRepositories]);

  const handleSelectRepo = async (fullName: string) => {
    setSelectedRepoFullName(fullName);
    setBranches([]);
    setSelectedBranch('');
    setInlineError(null);
    const repo = repositories.find((r) => r.full_name === fullName);
    if (!repo || !githubSession) return;
    setLoadingBranches(true);
    const [owner] = repo.full_name.split('/');
    const list = await fetchBranches(githubSession, owner, repo.name);
    setLoadingBranches(false);
    const resolved = list.length > 0 ? list : [repo.default_branch].filter(Boolean);
    setBranches(resolved);
    setSelectedBranch(repo.default_branch || resolved[0] || DEFAULT_BRANCH);
  };

  const handlePush = async () => {
    setInlineError(null);
    let config: SpecDrivenPushConfig;

    if (isUpdateMode && linkedRepo) {
      config = {
        useExisting: true,
        repoName: linkedRepo.repo,
        isPrivate,
        branch: linkedRepo.branch || DEFAULT_BRANCH,
        commitMessage: commitMessage.trim() || undefined,
      };
    } else if (mode === 'existing') {
      const repo = repositories.find((r) => r.full_name === selectedRepoFullName);
      if (!repo) {
        setInlineError('Select a repository to push to.');
        return;
      }
      config = {
        useExisting: true,
        repoName: repo.name,
        isPrivate: repo.private,
        branch: selectedBranch || repo.default_branch || DEFAULT_BRANCH,
        commitMessage: commitMessage.trim() || undefined,
      };
    } else {
      if (validateRepoName(repoName)) {
        validation.markTouched('repoName');
        return;
      }
      config = {
        useExisting: false,
        repoName: repoName.trim(),
        description: description.trim() || undefined,
        isPrivate,
        branch: createBranch.trim() || DEFAULT_BRANCH,
        commitMessage: commitMessage.trim() || undefined,
      };
    }

    const outcome = await push(config);
    if (!outcome.ok) {
      setInlineError(outcome.message);
      // A name clash → the repo already exists; drop the user into the picker
      // so they can push to it as an existing repo instead.
      if (outcome.code === 'conflict') {
        setMode('existing');
      }
    }
    // On success the hook updates ``result`` and this renders the success view.
  };

  const canSubmit =
    !isPushing &&
    (isUpdateMode
      ? true
      : mode === 'existing'
        ? !!selectedRepoFullName
        : validation.isValid);

  // ── Success view ───────────────────────────────────────────────────────
  if (result?.success) {
    return (
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Github className="size-5" />
              Pushed to GitHub
            </DialogTitle>
            <DialogDescription>
              {result.is_first_push ? 'Repository created and files pushed.' : 'Repository updated with your latest generation.'}
            </DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-3">
            <div className="rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-800 dark:border-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300">
              <p className="font-medium">
                {result.owner}/{result.repo_name}
              </p>
              <p className="text-xs">{result.files_uploaded} file{result.files_uploaded === 1 ? '' : 's'} uploaded.</p>
            </div>
            <a
              href={result.repo_url}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-sm font-medium text-brand underline"
            >
              <ExternalLink className="size-4" />
              View on GitHub
            </a>
          </div>
          <DialogFooter>
            <Button onClick={() => onOpenChange(false)}>Done</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    );
  }

  // ── Push form ──────────────────────────────────────────────────────────
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Github className="size-5" />
            Push to GitHub
          </DialogTitle>
          <DialogDescription>
            {isUpdateMode
              ? 'Update the linked repository with your latest generated code and model.'
              : 'Push the generated code and project model to a GitHub repository.'}
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-4">
          {isUpdateMode && linkedRepo ? (
            <>
              <div className="flex items-center justify-between rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-800 dark:border-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300">
                <div>
                  <p className="font-medium">
                    Linked to{' '}
                    <a
                      href={`https://github.com/${linkedRepo.owner}/${linkedRepo.repo}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="underline"
                    >
                      {linkedRepo.owner}/{linkedRepo.repo}
                    </a>
                    <span className="text-xs opacity-80">@{linkedRepo.branch || DEFAULT_BRANCH}</span>
                  </p>
                  <p className="text-xs">Re-pushing updates this repository.</p>
                </div>
                <Button variant="outline" size="sm" onClick={onChangeRepo} disabled={isPushing}>
                  Change repo
                </Button>
              </div>
              <FormField label="Commit Message" helperText="Describe what changed (optional).">
                <Input
                  value={commitMessage}
                  onChange={(event) => setCommitMessage(event.target.value)}
                  placeholder="Update generated app"
                />
              </FormField>
            </>
          ) : (
            <>
              {/* Create vs. existing toggle */}
              <div className="inline-flex w-full rounded-md border border-border/70 p-0.5 text-sm">
                <button
                  type="button"
                  onClick={() => setMode('create')}
                  className={`flex-1 rounded px-3 py-1.5 font-medium transition-colors ${
                    mode === 'create' ? 'bg-brand text-brand-foreground' : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  Create new repo
                </button>
                <button
                  type="button"
                  onClick={() => setMode('existing')}
                  className={`flex-1 rounded px-3 py-1.5 font-medium transition-colors ${
                    mode === 'existing' ? 'bg-brand text-brand-foreground' : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  Use existing repo
                </button>
              </div>

              {mode === 'create' ? (
                <>
                  <FormField label="Repository Name" required error={validation.getError('repoName')}>
                    <Input
                      value={repoName}
                      onChange={(event) => setRepoName(event.target.value)}
                      onBlur={() => validation.markTouched('repoName')}
                      placeholder="my-generated-app"
                      className={validation.getError('repoName') ? 'border-destructive focus-visible:border-destructive focus-visible:ring-destructive/20' : ''}
                    />
                  </FormField>
                  <FormField label="Description">
                    <Textarea
                      rows={2}
                      value={description}
                      onChange={(event) => setDescription(event.target.value)}
                      placeholder="Optional description..."
                    />
                  </FormField>
                  <label className="flex items-center justify-between gap-3 rounded-md border border-border/70 px-3 py-2 text-sm">
                    Private repository
                    <input
                      type="checkbox"
                      checked={isPrivate}
                      onChange={(event) => setIsPrivate(event.target.checked)}
                      className="size-4 rounded border-border"
                    />
                  </label>
                  {!isPrivate && (
                    <p className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800 dark:border-amber-800 dark:bg-amber-900/30 dark:text-amber-300">
                      This repository will be <strong>public</strong> — anyone can see the generated code and model.
                    </p>
                  )}
                </>
              ) : (
                <>
                  <FormField label="Repository" htmlFor="push-existing-repo">
                    <select
                      id="push-existing-repo"
                      value={selectedRepoFullName}
                      onChange={(event) => void handleSelectRepo(event.target.value)}
                      disabled={reposLoading}
                      className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"
                    >
                      <option value="" disabled>
                        {reposLoading ? 'Loading repositories…' : 'Select a repository'}
                      </option>
                      {repositories.map((repo) => (
                        <option key={repo.id} value={repo.full_name}>
                          {repo.full_name}
                          {repo.private ? ' (private)' : ''}
                        </option>
                      ))}
                    </select>
                  </FormField>
                  {selectedRepoFullName && (
                    <FormField label="Branch" htmlFor="push-existing-branch">
                      <select
                        id="push-existing-branch"
                        value={selectedBranch}
                        onChange={(event) => setSelectedBranch(event.target.value)}
                        disabled={loadingBranches}
                        className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"
                      >
                        {loadingBranches ? (
                          <option value="">Loading branches…</option>
                        ) : (
                          branches.map((branch) => (
                            <option key={branch} value={branch}>
                              {branch}
                            </option>
                          ))
                        )}
                      </select>
                    </FormField>
                  )}
                  <FormField label="Commit Message" helperText="Describe what changed (optional).">
                    <Input
                      value={commitMessage}
                      onChange={(event) => setCommitMessage(event.target.value)}
                      placeholder="Update generated app"
                    />
                  </FormField>
                </>
              )}
            </>
          )}

          {inlineError && (
            <p className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700 dark:border-red-800 dark:bg-red-950/30 dark:text-red-300">
              {inlineError}
            </p>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isPushing}>
            Cancel
          </Button>
          <Button
            onClick={() => void handlePush()}
            disabled={!canSubmit}
            className="gap-1.5 bg-brand text-brand-foreground hover:bg-brand-dark"
          >
            {isPushing ? <Loader2 className="size-4 animate-spin" /> : <Github className="size-4" />}
            {isPushing ? 'Pushing…' : isUpdateMode ? 'Push update' : 'Push to GitHub'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
