import React from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';

interface LinkedRepo {
  owner: string;
  repo: string;
}

interface DeployDialogProps {
  open: boolean;
  isDeploying: boolean;
  repoName: string;
  repoDescription: string;
  repoPrivate: boolean;
  useExistingRepo: boolean;
  linkedRepo: LinkedRepo | null;
  commitMessage: string;
  onOpenChange: (open: boolean) => void;
  onRepoNameChange: (value: string) => void;
  onRepoDescriptionChange: (value: string) => void;
  onRepoPrivateChange: (value: boolean) => void;
  onCommitMessageChange: (value: string) => void;
  onCreateNewInstead: () => void;
  onPublish: () => void;
}

export const DeployDialog: React.FC<DeployDialogProps> = ({
  open,
  isDeploying,
  repoName,
  repoDescription,
  repoPrivate,
  useExistingRepo,
  linkedRepo,
  commitMessage,
  onOpenChange,
  onRepoNameChange,
  onRepoDescriptionChange,
  onRepoPrivateChange,
  onCommitMessageChange,
  onCreateNewInstead,
  onPublish,
}) => {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>Publish to Render</DialogTitle>
          <DialogDescription>
            {useExistingRepo
              ? 'Update the existing repository with your latest changes.'
              : 'Create a GitHub repository from the current project and deploy it on Render.'}
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4">
          {useExistingRepo && linkedRepo ? (
            <>
              <div className="flex items-center justify-between rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-800">
                <div>
                  <p className="font-medium">
                    Previously deployed to:{' '}
                    <a
                      href={`https://github.com/${linkedRepo.owner}/${linkedRepo.repo}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="underline"
                    >
                      {linkedRepo.owner}/{linkedRepo.repo}
                    </a>
                  </p>
                  <p className="text-xs">Files you added manually will be preserved.</p>
                </div>
                <Button variant="outline" size="sm" onClick={onCreateNewInstead}>
                  Create new repo instead
                </Button>
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="deploy-commit-message">Commit Message</Label>
                <Input
                  id="deploy-commit-message"
                  value={commitMessage}
                  onChange={(event) => onCommitMessageChange(event.target.value)}
                  placeholder="Update app"
                />
                <p className="text-xs text-muted-foreground">Describe what changed (leave empty for default message)</p>
              </div>
            </>
          ) : (
            <>
              <div className="space-y-1.5">
                <Label htmlFor="deploy-repo-name">Repository Name</Label>
                <Input
                  id="deploy-repo-name"
                  value={repoName}
                  onChange={(event) => onRepoNameChange(event.target.value)}
                  placeholder="my-awesome-app"
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="deploy-repo-description">Description</Label>
                <Input
                  id="deploy-repo-description"
                  value={repoDescription}
                  onChange={(event) => onRepoDescriptionChange(event.target.value)}
                  placeholder="Web application generated by BESSER"
                />
              </div>
              <label className="flex items-center justify-between gap-3 rounded-md border border-border/70 px-3 py-2 text-sm">
                Make repository private
                <input
                  type="checkbox"
                  checked={repoPrivate}
                  onChange={(event) => onRepoPrivateChange(event.target.checked)}
                />
              </label>
              {repoPrivate && (
                <p className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
                  Private repositories may require manual Render permission setup.
                </p>
              )}
            </>
          )}
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isDeploying}>
            Cancel
          </Button>
          <Button onClick={onPublish} disabled={isDeploying || !repoName.trim()}>
            {isDeploying ? 'Publishing...' : useExistingRepo ? 'Update & Publish' : 'Publish to Render'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
