import React from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';

interface DeployDialogProps {
  open: boolean;
  isDeploying: boolean;
  repoName: string;
  repoDescription: string;
  repoPrivate: boolean;
  onOpenChange: (open: boolean) => void;
  onRepoNameChange: (value: string) => void;
  onRepoDescriptionChange: (value: string) => void;
  onRepoPrivateChange: (value: boolean) => void;
  onPublish: () => void;
}

export const DeployDialog: React.FC<DeployDialogProps> = ({
  open,
  isDeploying,
  repoName,
  repoDescription,
  repoPrivate,
  onOpenChange,
  onRepoNameChange,
  onRepoDescriptionChange,
  onRepoPrivateChange,
  onPublish,
}) => {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>Publish to Render</DialogTitle>
          <DialogDescription>Create a GitHub repository from the current project and deploy it on Render.</DialogDescription>
        </DialogHeader>
        <div className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="deploy-repo-name">Repository Name</Label>
            <Input
              id="deploy-repo-name"
              value={repoName}
              onChange={(event) => onRepoNameChange(event.target.value)}
              placeholder="my-awesome-app"
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="deploy-repo-description">Description</Label>
            <Input
              id="deploy-repo-description"
              value={repoDescription}
              onChange={(event) => onRepoDescriptionChange(event.target.value)}
              placeholder="Web application generated by BESSER"
            />
          </div>
          <label className="flex items-center justify-between gap-3 rounded-md border border-border/70 px-3 py-2 text-sm">
            Make repository private
            <input
              type="checkbox"
              checked={repoPrivate}
              onChange={(event) => onRepoPrivateChange(event.target.checked)}
            />
          </label>
          {repoPrivate && (
            <p className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
              Private repositories may require manual Render permission setup.
            </p>
          )}
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isDeploying}>
            Cancel
          </Button>
          <Button onClick={onPublish} disabled={isDeploying || !repoName.trim()}>
            {isDeploying ? 'Publishing...' : 'Publish to Render'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
