import { UMLDiagramType } from '@besser/wme';
import type { SupportedDiagramType } from '../../types/project';
import type { GeneratorMenuMode, GeneratorType } from '../sidebar/workspace-types';

export interface WorkspaceTopBarProps {
  isDarkTheme: boolean;
  headerBackgroundClass: string;
  topPanelClass: string;
  topPanelIconClass: string;
  diagramBadgeClass: string;
  outlineButtonClass: string;
  primaryGenerateClass: string;
  showQualityCheck: boolean;
  generatorMode: GeneratorMenuMode;
  isGenerating: boolean;
  projectNameDraft: string;
  diagramTitleDraft: string;
  currentDiagramType?: string;
  locationPath: string;
  activeUmlType: UMLDiagramType;
  isAuthenticated: boolean;
  username?: string;
  githubLoading: boolean;
  hasProject: boolean;
  isDeploymentAvailable: boolean;
  onOpenProjectHub: () => void;
  onOpenTemplateDialog: () => void;
  onExportProject: () => void;
  onImportSingleDiagram: () => void;
  onOpenAssistantImportImage: () => void;
  onOpenAssistantImportKg: () => void;
  onOpenProjectPreview: () => void;
  onGenerate: (type: GeneratorType) => void;
  onQualityCheck: () => void;
  onToggleTheme: () => void;
  onGitHubLogin: () => void;
  onGitHubLogout: () => void;
  onOpenGitHubSidebar: () => void;
  hasStarred: boolean;
  starLoading: boolean;
  onToggleStar: () => void;
  onOpenDeployDialog: () => void;
  onOpenHelpDialog: () => void;
  onOpenAboutDialog: () => void;
  onOpenFeedback: () => void;
  onOpenKeyboardShortcuts: () => void;
  activeDiagramType: SupportedDiagramType;
  onSwitchUml: (type: UMLDiagramType) => void;
  onSwitchDiagramType: (type: SupportedDiagramType) => void;
  onNavigate: (path: string) => void;
  onProjectNameDraftChange: (value: string) => void;
  onProjectRename: () => void;
  onDiagramTitleDraftChange: (value: string) => void;
  onDiagramRename: () => void;
}
