export type GeneratorType =
  | 'django'
  | 'backend'
  | 'web_app'
  | 'sql'
  | 'supabase'
  | 'sqlalchemy'
  | 'python'
  | 'java'
  | 'pydantic'
  | 'jsonschema'
  | 'smartdata'
  | 'agent'
  | 'qiskit'
  | 'jsonobject'
  | 'pytorch'
  | 'tensorflow'
  | 'bpmn'
  | 'test_case'
  | 'kg_to_class'
  | 'kg_refine'
  | 'kg_export_owl'
  | 'kg_export_ttl'
  | 'kg_export_with_options';

export type GeneratorMenuMode =
  | 'class'
  | 'object'
  | 'user'
  | 'statemachine'
  | 'agent'
  | 'gui'
  | 'quantum'
  | 'nn'
  | 'bpmn'
  | 'kg'
  | 'none';
