import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { toast } from 'react-toastify';
import { useGitHubAuth } from '../../../features/github/hooks/useGitHubAuth';
import { useDeployToGitHub, type DeploymentTarget } from '../../../features/github/hooks/useGitHubDeploy';
import { ProjectStorageRepository } from '../../../shared/services/storage/ProjectStorageRepository';
import { buildProjectPayloadForBackend } from '../../../features/export/utils/projectExportUtils';
import type { BesserProject } from '../../../shared/types/project';
import { getPostHog } from '../../../shared/services/analytics/lazy-analytics';
import {
  buildPersonalizationMapping,
  hasPersonalizationVariants,
} from '../../../features/deploy/utils/agentPersonalizationPayload';
import { restoreBaseAgentModels } from '../../../features/deploy/utils/restoreBaseAgentModels';

// localStorage helpers for tracking previously deployed repos per project
const DEPLOY_LINKED_REPO_PREFIX = 'besser_deploy_linked_';

function getDeployLinkedRepo(projectId: string, target: DeploymentTarget): { owner: string; repo: string } | null {
  try {
    const scopedKey = `${DEPLOY_LINKED_REPO_PREFIX}${projectId}_${target}`;
    let raw = localStorage.getItem(scopedKey);
    if (!raw && target === 'agent') {
      // Backward compatibility with previously stored agent deployments.
      raw = localStorage.getItem(`${DEPLOY_LINKED_REPO_PREFIX}${projectId}_chatbot`);
    }
    if (!raw && target === 'webapp') {
      // Backward compatibility with previously stored webapp deployments.
      raw = localStorage.getItem(`${DEPLOY_LINKED_REPO_PREFIX}${projectId}`);
    }
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (parsed && parsed.owner && parsed.repo) return parsed;
    return null;
  } catch {
    return null;
  }
}

function saveDeployLinkedRepo(projectId: string, target: DeploymentTarget, owner: string, repo: string): void {
  localStorage.setItem(`${DEPLOY_LINKED_REPO_PREFIX}${projectId}_${target}`, JSON.stringify({ owner, repo }));
}

function clearDeployLinkedRepo(projectId: string, target: DeploymentTarget): void {
  localStorage.removeItem(`${DEPLOY_LINKED_REPO_PREFIX}${projectId}_${target}`);
  if (target === 'agent') {
    localStorage.removeItem(`${DEPLOY_LINKED_REPO_PREFIX}${projectId}_chatbot`);
  }
  if (target === 'webapp') {
    localStorage.removeItem(`${DEPLOY_LINKED_REPO_PREFIX}${projectId}`);
  }
}

const sanitizeRepoName = (name: string): string => {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '');
};

const hasWebAppDeploymentInputs = (project: BesserProject | null): boolean => {
  if (!project) return false;
  const hasClassDiagram = project.diagrams.ClassDiagram.some((diagram) => Boolean(diagram?.model));
  const hasGuiDiagram = project.diagrams.GUINoCodeDiagram.some((diagram) => Boolean(diagram?.model));
  return hasClassDiagram && hasGuiDiagram;
};

const hasAgentDeploymentInputs = (project: BesserProject | null): boolean => {
  if (!project) return false;
  return project.diagrams.AgentDiagram.some((diagram) => {
    if (!diagram?.model || typeof diagram.model !== 'object') return false;
    const modelWithElements = diagram.model as { elements?: Record<string, unknown> };
    return Boolean(modelWithElements.elements && Object.keys(modelWithElements.elements).length > 0);
  });
};

const defaultRepoNameForTarget = (projectName: string, target: DeploymentTarget): string => {
  const baseName = sanitizeRepoName(projectName || '');
  if (target === 'agent') {
    if (!baseName) return 'besser-agent';
    return baseName.endsWith('-agent') ? baseName : `${baseName}-agent`;
  }
  return baseName || 'besser-webapp';
};

const defaultDescriptionForTarget = (target: DeploymentTarget): string => (
  target === 'agent'
    ? 'Standalone agent generated by BESSER'
    : 'Web application generated by BESSER'
);

interface UseDeploymentOptions {
  currentProject: BesserProject | null;
  isDeploymentAvailable: boolean;
}

export function useDeployment({ currentProject, isDeploymentAvailable }: UseDeploymentOptions) {
  const {
    isAuthenticated,
    githubSession,
  } = useGitHubAuth();
  const { deployToGitHub, isDeploying: isDeployingToRender, deploymentResult } = useDeployToGitHub();

  const [isDeployDialogOpen, setIsDeployDialogOpen] = useState(false);
  const [isDeployResultOpen, setIsDeployResultOpen] = useState(false);
  const [githubRepoName, setGithubRepoName] = useState('');
  const [githubRepoDescription, setGithubRepoDescription] = useState('');
  const [githubRepoPrivate, setGithubRepoPrivate] = useState(false);
  const [useExistingRepo, setUseExistingRepo] = useState(false);
  const [linkedRepo, setLinkedRepo] = useState<{ owner: string; repo: string } | null>(null);
  const [commitMessage, setCommitMessage] = useState('');
  const [deploymentTarget, setDeploymentTarget] = useState<DeploymentTarget>('webapp');
  const [includePersonalization, setIncludePersonalization] = useState(false);

  const showPersonalizationOption = useMemo(
    () => hasPersonalizationVariants(currentProject),
    [currentProject],
  );

  // If variants disappear (diagram switched, variants cleared), drop the toggle
  // so we never send a stale mapping to the backend.
  useEffect(() => {
    if (!showPersonalizationOption && includePersonalization) {
      setIncludePersonalization(false);
    }
  }, [showPersonalizationOption, includePersonalization]);

  const availableDeployTargets = useMemo<DeploymentTarget[]>(() => {
    const targets: DeploymentTarget[] = [];
    if (hasWebAppDeploymentInputs(currentProject)) {
      targets.push('webapp');
    }
    if (hasAgentDeploymentInputs(currentProject)) {
      targets.push('agent');
    }
    return targets;
  }, [currentProject]);

  // Reset linked repo state when project/target changes.
  useEffect(() => {
    if (currentProject) {
      const linked = getDeployLinkedRepo(currentProject.id, deploymentTarget);
      setLinkedRepo(linked);
      setUseExistingRepo(!!linked);
    } else {
      setLinkedRepo(null);
      setUseExistingRepo(false);
    }
  }, [currentProject?.id, deploymentTarget]);

  const handleOpenDeployDialog = useCallback(() => {
    if (!isDeploymentAvailable) {
      toast.info('Deploy is available for Web App and Agent diagrams.');
      return;
    }
    if (!isAuthenticated) {
      toast.info('Connect to GitHub first.');
      return;
    }
    if (!currentProject) {
      toast.error('Create or load a project first.');
      return;
    }

    if (availableDeployTargets.length === 0) {
      toast.info('Deploy requires Class + GUI diagrams (Web App) or at least one Agent diagram (Standalone Agent).');
      return;
    }

    const initialTarget = availableDeployTargets.includes(deploymentTarget)
      ? deploymentTarget
      : availableDeployTargets[0];
    setDeploymentTarget(initialTarget);

    setCommitMessage('');
    const linked = getDeployLinkedRepo(currentProject.id, initialTarget);
    if (linked) {
      setLinkedRepo(linked);
      setGithubRepoName(linked.repo);
      setUseExistingRepo(true);
    } else {
      setLinkedRepo(null);
      setUseExistingRepo(false);
      setGithubRepoName(defaultRepoNameForTarget(currentProject.name, initialTarget));
    }
    setGithubRepoDescription(defaultDescriptionForTarget(initialTarget));
    setGithubRepoPrivate(false);
    setIsDeployDialogOpen(true);
  }, [isDeploymentAvailable, isAuthenticated, currentProject, availableDeployTargets, deploymentTarget]);

  const handleOpenDeployDialogRef = useRef(handleOpenDeployDialog);
  handleOpenDeployDialogRef.current = handleOpenDeployDialog;

  // Listen for assistant-driven deploy event
  useEffect(() => {
    const handleAssistantDeploy = (_e: Event) => {
      handleOpenDeployDialogRef.current();
    };

    window.addEventListener('wme:assistant-deploy-app', handleAssistantDeploy);
    return () => window.removeEventListener('wme:assistant-deploy-app', handleAssistantDeploy);
  }, []);

  const handleDeploymentTargetChange = useCallback((target: DeploymentTarget) => {
    setDeploymentTarget(target);
    // Reset personalization toggle when switching targets — it only applies to
    // agent deploys, and a stale "on" from a previous agent session
    // shouldn't leak into a fresh webapp -> agent switch.
    if (target !== 'agent') {
      setIncludePersonalization(false);
    }
    if (!currentProject) {
      return;
    }

    const linked = getDeployLinkedRepo(currentProject.id, target);
    if (linked) {
      setLinkedRepo(linked);
      setUseExistingRepo(true);
      setGithubRepoName(linked.repo);
    } else {
      setLinkedRepo(null);
      setUseExistingRepo(false);
      setGithubRepoName(defaultRepoNameForTarget(currentProject.name, target));
    }
    setGithubRepoDescription(defaultDescriptionForTarget(target));
    setCommitMessage('');
  }, [currentProject]);

  const handlePublishToRender = useCallback(async () => {
    if (!currentProject) {
      toast.error('No project available for deployment.');
      return;
    }
    if (!githubSession) {
      toast.error('GitHub session not found. Please reconnect.');
      return;
    }
    if (!githubRepoName.trim()) {
      toast.error('Repository name is required.');
      return;
    }

    const projectForDeploy = ProjectStorageRepository.loadProject(currentProject.id) || currentProject;

    let personalizationMapping: Array<Record<string, unknown>> | null = null;
    if (deploymentTarget === 'agent' && includePersonalization) {
      const mapping = buildPersonalizationMapping(projectForDeploy);
      if (mapping.length === 0) {
        toast.error('No valid personalization mappings found. Save personalized variants before enabling this option.');
        return;
      }
      personalizationMapping = mapping as unknown as Array<Record<string, unknown>>;
    }

    // Webapp deploys embed the agent model directly in the generated app, so
    // always ship the base (pre-personalization) snapshot — even if the user
    // has applied personalization to the active AgentDiagram in the editor.
    const projectForPayload = deploymentTarget === 'webapp'
      ? restoreBaseAgentModels(projectForDeploy)
      : projectForDeploy;

    const result = await deployToGitHub(
      buildProjectPayloadForBackend(projectForPayload),
      sanitizeRepoName(githubRepoName),
      githubRepoDescription.trim() || defaultDescriptionForTarget(deploymentTarget),
      githubRepoPrivate,
      githubSession,
      useExistingRepo,
      commitMessage,
      deploymentTarget,
      personalizationMapping,
    );

    if (result?.success) {
      saveDeployLinkedRepo(currentProject.id, deploymentTarget, result.owner, result.repo_name);
      setIsDeployDialogOpen(false);
      setIsDeployResultOpen(true);

      getPostHog()?.capture('render_deploy_success', {
        deployment_status: 'success',
        is_private: githubRepoPrivate,
        repo_name: githubRepoName,
        repo_url: result.repo_url,
        owner: result.owner,
        files_uploaded: result.files_uploaded,
        is_redeployment: useExistingRepo,
        diagram_type: currentProject.currentDiagramType,
        deployment_target: deploymentTarget,
      });
    } else {
      getPostHog()?.capture('render_deploy_failure', {
        deployment_status: 'failed',
        is_private: githubRepoPrivate,
        repo_name: githubRepoName,
        diagram_type: currentProject.currentDiagramType,
        deployment_target: deploymentTarget,
      });
    }
  }, [currentProject, githubSession, githubRepoName, githubRepoDescription, githubRepoPrivate, useExistingRepo, commitMessage, deployToGitHub, deploymentTarget]);

  const handleCreateNewInstead = useCallback(() => {
    if (currentProject?.id) {
      clearDeployLinkedRepo(currentProject.id, deploymentTarget);
    }
    setLinkedRepo(null);
    setUseExistingRepo(false);
    setGithubRepoName(defaultRepoNameForTarget(currentProject?.name || '', deploymentTarget));
  }, [currentProject, deploymentTarget]);

  return {
    // State
    isDeployDialogOpen,
    isDeployResultOpen,
    githubRepoName,
    githubRepoDescription,
    githubRepoPrivate,
    useExistingRepo,
    linkedRepo,
    commitMessage,
    deploymentTarget,
    availableDeployTargets,
    isDeployingToRender,
    deploymentResult,
    includePersonalization,
    showPersonalizationOption,

    // Setters
    setIsDeployDialogOpen,
    setIsDeployResultOpen,
    setGithubRepoName,
    setGithubRepoDescription,
    setGithubRepoPrivate,
    setCommitMessage,
    setIncludePersonalization,

    // Handlers
    handleOpenDeployDialog,
    handleDeploymentTargetChange,
    handlePublishToRender,
    handleCreateNewInstead,
  };
}
